server:
  port: 8063
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/album_db?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: ENC(9DNSpGg2nImv9jTMdz+ORy1Ay9BqgTicdesjuHfCgE5/gq963xUWkDtXjVi3F1gq)
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources/static
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8 # 编码
    suffix: .html # 模板后缀
    mode: HTML # 模板
  application:
    name: album

mybatis:
  type-aliases-package: cool.wangshuo.album.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(-){faint} %clr([%14.14t]){faint} %clr(%-40.40logger.%13.13M){cyan} %clr(%3.3L) %clr(:){faint} %msg%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"


# 自定义配置信息：图片保存地址
image:
  # 相册内的图片的保存位置
  path: E:\MyProject\IdeaProject\album_springboot\album_springboot\src\main\resources\static\images
  # 相册封面保存路径
  face: E:\MyProject\IdeaProject\album_springboot\album_springboot\src\main\resources\static\faceImage